### ISSUE TITLE
Support for autoresize

### ISSUE THREAD

**Issue by remiserriere** [MyCaffe/WebCam#3]
Hello, I cloned your repo and made a few changes to WebCam.cs to subscribe to the PictureBox SizeChanged event, so the video window size is being updated, matching the pb size. 
Feel free to add this to your code ;)
[WebCam.txt](https://github.com/MyCaffe/WebCam/files/5316768/WebCam.txt)

Congrats for this project!

**Comment by ZoroDerVonCodier** [comment]
Hi @remiserriere ,

We will take a look and see if we can get this into the next release - thanks for the input!  I'll let you know when we add this.

**Comment by ZoroDerVonCodier** [comment]
Hi @remiserriere ,

Thanks for the input, we added your resizing suggestions - pretty cool!  This will also be included in the next Nuget release.

Let me know whether or not the new additions work on your side and if so, I will close this out.
