### ISSUE TITLE
Camera resolution selection

### ISSUE THREAD

**Issue by GabrielBottari** [MyCaffe/WebCam#4]
I'm wondering how much work it would be to implement camera resolution selection. Right now the filter just starts on what seems to be the default resolution. Maybe we could have a different filter for each resolution?

@ZoroDerVonCodier What do you think?

**Comment by ZoroDerVonCodier** [comment]
@GabrielBottari ,

I will look into that next week and let you know what I think.  Are the resolutions that you are talking about provided by the device?  You are correct, that I currently use the default.

**Comment by GabrielBottari** [comment]
Yes that's correct. A webcam can provide different camera resolutions to record from. AForge which uses DirectShow has a similar implementation [as seen here](http://www.aforgenet.com/framework/docs/html/ff97965b-2ca0-7b5e-8223-dd13b3b91619.htm).

**Comment by ZoroDerVonCodier** [comment]
Hi @GabrielBottari ,

I have added an option to the Open method that allows you to set the resolution via a configuration dialog provided by DirectShow.  Just check the 'Select resolution on connect' check box before connecting.  This only works with the web cams and not a video file.

Let me know if this is what you were looking for.

Hope this helps!

**Comment by GabrielBottari** [comment]
That's really nice! Although I was wondering if that would be possible programmatically? My face recognition ml model works with 480p images, therefore I'd like to restrict the resolution in code to reduce CPU usage.

Would that be possible?

Worst case scenario I could maybe hide the dialog and click it programmatically 🤔

**Comment by ZoroDerVonCodier** [comment]
Hi @GabrielBottari ,

I kind of figured you would want that!  I have a solution that I am just finishing up my testing on and should have ready soon.

**Comment by ZoroDerVonCodier** [comment]
Hi @GabrielBottari ,

Check out the latest on Git.  The WebCam now has a new method 'GetVideoCapabilities' that returns a collection of VideoCapability objects that specify the HxW and FPS options.  From there you can select one of the VideoCapability objects and pass it into the Open method and that capability will be used.  Otherwise if the video capability sent to Open is null, the default will be used.

Let me know how this works for you.  And if you have a web-site showing your project, let me know, I'd love to see it!

Hope this helps!

**Comment by ZoroDerVonCodier** [comment]
@GabrielBottari ,

Let me know if this worked for you and I will close this out after you confirm.

**Comment by GabrielBottari** [comment]
@ZoroDerVonCodier ,

Sorry for the slow response.. Had a lot of things to deal with recently. But I had time to integrate your new changes, and oh boy it works well! I've been able to reduce cpu usage to basically 0. It's a private project, but I have invited you with a read permission for you to check out 😃 

repo: https://github.com/chocolat-chaud-io/protector
pr integrating your new functionality: https://github.com/chocolat-chaud-io/protector/pull/12

As you can see, I added an extension method in my code to get the closest resolution to a given resolution. Because knowing the exact match is unlikely. For example my camera had only 2 resolutions available.

Cheers!

**Comment by ZoroDerVonCodier** [comment]
@GabrielBottari ,
Glad to hear it works well!  Thank you for the invite, that looks like a pretty cool project!
